CREATE DATABASE IF NOT EXISTS espana2084
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'espana2084'@'localhost'
  IDENTIFIED BY 'espana2084';

GRANT ALL PRIVILEGES ON espana2084.* TO 'espana2084'@'localhost';
FLUSH PRIVILEGES;
