CREATE DATABASE IF NOT EXISTS iberia2084
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'iberia2084'@'localhost'
  IDENTIFIED BY 'iberia2084';

GRANT ALL PRIVILEGES ON iberia2084.* TO 'iberia2084'@'localhost';
FLUSH PRIVILEGES;
